// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cache.sql

package dbgen

import (
	"context"
)

const getWidgetCache = `-- name: GetWidgetCache :one
SELECT widget_id, data_json, fetched_at, expires_at, status, error_msg FROM widget_cache WHERE widget_id = ?
`

func (q *Queries) GetWidgetCache(ctx context.Context, widgetID int64) (WidgetCache, error) {
	row := q.db.QueryRowContext(ctx, getWidgetCache, widgetID)
	var i WidgetCache
	err := row.Scan(
		&i.WidgetID,
		&i.DataJson,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.ErrorMsg,
	)
	return i, err
}

const listExpiredWidgetIDs = `-- name: ListExpiredWidgetIDs :many
SELECT id FROM widgets
WHERE id NOT IN (SELECT widget_id FROM widget_cache)
   OR id IN (SELECT widget_id FROM widget_cache WHERE expires_at <= datetime('now'))
`

func (q *Queries) ListExpiredWidgetIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredWidgetIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWidgetCacheStale = `-- name: MarkWidgetCacheStale :exec
UPDATE widget_cache SET status = 'stale', error_msg = ? WHERE widget_id = ?
`

type MarkWidgetCacheStaleParams struct {
	ErrorMsg string `json:"error_msg"`
	WidgetID int64  `json:"widget_id"`
}

func (q *Queries) MarkWidgetCacheStale(ctx context.Context, arg MarkWidgetCacheStaleParams) error {
	_, err := q.db.ExecContext(ctx, markWidgetCacheStale, arg.ErrorMsg, arg.WidgetID)
	return err
}

const upsertWidgetCache = `-- name: UpsertWidgetCache :exec
INSERT INTO widget_cache (widget_id, data_json, fetched_at, expires_at, status, error_msg)
VALUES (?, ?, datetime('now'), ?, ?, ?)
ON CONFLICT(widget_id) DO UPDATE SET
    data_json = excluded.data_json,
    fetched_at = excluded.fetched_at,
    expires_at = excluded.expires_at,
    status = excluded.status,
    error_msg = excluded.error_msg
`

type UpsertWidgetCacheParams struct {
	WidgetID  int64  `json:"widget_id"`
	DataJson  string `json:"data_json"`
	ExpiresAt string `json:"expires_at"`
	Status    string `json:"status"`
	ErrorMsg  string `json:"error_msg"`
}

func (q *Queries) UpsertWidgetCache(ctx context.Context, arg UpsertWidgetCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertWidgetCache,
		arg.WidgetID,
		arg.DataJson,
		arg.ExpiresAt,
		arg.Status,
		arg.ErrorMsg,
	)
	return err
}
