// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: datasources.sql

package dbgen

import (
	"context"
)

const addWidgetSource = `-- name: AddWidgetSource :one
INSERT INTO widget_sources (widget_id, data_source_id, filter, position)
VALUES (?, ?, ?, ?)
RETURNING id, widget_id, data_source_id, "filter", resource, color, position
`

type AddWidgetSourceParams struct {
	WidgetID     int64  `json:"widget_id"`
	DataSourceID int64  `json:"data_source_id"`
	Filter       string `json:"filter"`
	Position     int64  `json:"position"`
}

func (q *Queries) AddWidgetSource(ctx context.Context, arg AddWidgetSourceParams) (WidgetSource, error) {
	row := q.db.QueryRowContext(ctx, addWidgetSource,
		arg.WidgetID,
		arg.DataSourceID,
		arg.Filter,
		arg.Position,
	)
	var i WidgetSource
	err := row.Scan(
		&i.ID,
		&i.WidgetID,
		&i.DataSourceID,
		&i.Filter,
		&i.Resource,
		&i.Color,
		&i.Position,
	)
	return i, err
}

const createDataSource = `-- name: CreateDataSource :one
INSERT INTO data_sources (name, type, config_json, secret_ciphertext)
VALUES (?, ?, ?, ?)
RETURNING id, name, type, config_json, secret_ciphertext, oauth_status, access_expiry, last_sync, last_error, health, created_at, updated_at
`

type CreateDataSourceParams struct {
	Name             string `json:"name"`
	Type             string `json:"type"`
	ConfigJson       string `json:"config_json"`
	SecretCiphertext string `json:"secret_ciphertext"`
}

func (q *Queries) CreateDataSource(ctx context.Context, arg CreateDataSourceParams) (DataSource, error) {
	row := q.db.QueryRowContext(ctx, createDataSource,
		arg.Name,
		arg.Type,
		arg.ConfigJson,
		arg.SecretCiphertext,
	)
	var i DataSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ConfigJson,
		&i.SecretCiphertext,
		&i.OauthStatus,
		&i.AccessExpiry,
		&i.LastSync,
		&i.LastError,
		&i.Health,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDataSource = `-- name: DeleteDataSource :exec
DELETE FROM data_sources WHERE id = ?
`

func (q *Queries) DeleteDataSource(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDataSource, id)
	return err
}

const deleteWidgetSource = `-- name: DeleteWidgetSource :exec
DELETE FROM widget_sources WHERE id = ?
`

func (q *Queries) DeleteWidgetSource(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWidgetSource, id)
	return err
}

const getDataSource = `-- name: GetDataSource :one
SELECT id, name, type, config_json, secret_ciphertext, oauth_status, access_expiry, last_sync, last_error, health, created_at, updated_at FROM data_sources WHERE id = ?
`

func (q *Queries) GetDataSource(ctx context.Context, id int64) (DataSource, error) {
	row := q.db.QueryRowContext(ctx, getDataSource, id)
	var i DataSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ConfigJson,
		&i.SecretCiphertext,
		&i.OauthStatus,
		&i.AccessExpiry,
		&i.LastSync,
		&i.LastError,
		&i.Health,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDataSources = `-- name: ListDataSources :many
SELECT id, name, type, config_json, secret_ciphertext, oauth_status, access_expiry, last_sync, last_error, health, created_at, updated_at FROM data_sources ORDER BY name
`

func (q *Queries) ListDataSources(ctx context.Context) ([]DataSource, error) {
	rows, err := q.db.QueryContext(ctx, listDataSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DataSource{}
	for rows.Next() {
		var i DataSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.ConfigJson,
			&i.SecretCiphertext,
			&i.OauthStatus,
			&i.AccessExpiry,
			&i.LastSync,
			&i.LastError,
			&i.Health,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWidgetSources = `-- name: ListWidgetSources :many
SELECT ws.id, ws.widget_id, ws.data_source_id, ws.filter, ws.resource, ws.color, ws.position,
       ds.name AS source_name, ds.type AS source_type, ds.config_json AS source_config,
       ds.secret_ciphertext AS source_secret
FROM widget_sources ws
JOIN data_sources ds ON ds.id = ws.data_source_id
WHERE ws.widget_id = ?
ORDER BY ws.position, ws.id
`

type ListWidgetSourcesRow struct {
	ID           int64  `json:"id"`
	WidgetID     int64  `json:"widget_id"`
	DataSourceID int64  `json:"data_source_id"`
	Filter       string `json:"filter"`
	Resource     string `json:"resource"`
	Color        string `json:"color"`
	Position     int64  `json:"position"`
	SourceName   string `json:"source_name"`
	SourceType   string `json:"source_type"`
	SourceConfig string `json:"source_config"`
	SourceSecret string `json:"source_secret"`
}

func (q *Queries) ListWidgetSources(ctx context.Context, widgetID int64) ([]ListWidgetSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listWidgetSources, widgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWidgetSourcesRow{}
	for rows.Next() {
		var i ListWidgetSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.WidgetID,
			&i.DataSourceID,
			&i.Filter,
			&i.Resource,
			&i.Color,
			&i.Position,
			&i.SourceName,
			&i.SourceType,
			&i.SourceConfig,
			&i.SourceSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDataSourceSynced = `-- name: MarkDataSourceSynced :exec
UPDATE data_sources SET last_sync = datetime('now') WHERE id = ?
`

func (q *Queries) MarkDataSourceSynced(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markDataSourceSynced, id)
	return err
}

const maxWidgetSourcePosition = `-- name: MaxWidgetSourcePosition :one
SELECT CAST(COALESCE(MAX(position), -1) AS INTEGER) FROM widget_sources WHERE widget_id = ?
`

func (q *Queries) MaxWidgetSourcePosition(ctx context.Context, widgetID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxWidgetSourcePosition, widgetID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateDataSourceConfig = `-- name: UpdateDataSourceConfig :exec
UPDATE data_sources SET config_json = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateDataSourceConfigParams struct {
	ConfigJson string `json:"config_json"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateDataSourceConfig(ctx context.Context, arg UpdateDataSourceConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateDataSourceConfig, arg.ConfigJson, arg.ID)
	return err
}

const updateDataSourceHealth = `-- name: UpdateDataSourceHealth :exec
UPDATE data_sources
SET access_expiry = ?, last_error = ?, health = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateDataSourceHealthParams struct {
	AccessExpiry string `json:"access_expiry"`
	LastError    string `json:"last_error"`
	Health       string `json:"health"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateDataSourceHealth(ctx context.Context, arg UpdateDataSourceHealthParams) error {
	_, err := q.db.ExecContext(ctx, updateDataSourceHealth,
		arg.AccessExpiry,
		arg.LastError,
		arg.Health,
		arg.ID,
	)
	return err
}

const updateDataSourceName = `-- name: UpdateDataSourceName :exec
UPDATE data_sources SET name = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateDataSourceNameParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateDataSourceName(ctx context.Context, arg UpdateDataSourceNameParams) error {
	_, err := q.db.ExecContext(ctx, updateDataSourceName, arg.Name, arg.ID)
	return err
}

const updateDataSourceSecret = `-- name: UpdateDataSourceSecret :exec
UPDATE data_sources SET secret_ciphertext = ?, oauth_status = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateDataSourceSecretParams struct {
	SecretCiphertext string `json:"secret_ciphertext"`
	OauthStatus      string `json:"oauth_status"`
	ID               int64  `json:"id"`
}

func (q *Queries) UpdateDataSourceSecret(ctx context.Context, arg UpdateDataSourceSecretParams) error {
	_, err := q.db.ExecContext(ctx, updateDataSourceSecret, arg.SecretCiphertext, arg.OauthStatus, arg.ID)
	return err
}

const updateWidgetSourceColor = `-- name: UpdateWidgetSourceColor :exec
UPDATE widget_sources SET color = ? WHERE id = ?
`

type UpdateWidgetSourceColorParams struct {
	Color string `json:"color"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateWidgetSourceColor(ctx context.Context, arg UpdateWidgetSourceColorParams) error {
	_, err := q.db.ExecContext(ctx, updateWidgetSourceColor, arg.Color, arg.ID)
	return err
}

const updateWidgetSourceResource = `-- name: UpdateWidgetSourceResource :exec
UPDATE widget_sources SET resource = ? WHERE id = ?
`

type UpdateWidgetSourceResourceParams struct {
	Resource string `json:"resource"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateWidgetSourceResource(ctx context.Context, arg UpdateWidgetSourceResourceParams) error {
	_, err := q.db.ExecContext(ctx, updateWidgetSourceResource, arg.Resource, arg.ID)
	return err
}
