// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: widgets.sql

package dbgen

import (
	"context"
)

const createWidget = `-- name: CreateWidget :one
INSERT INTO widgets (name, type, config_json)
VALUES (?, ?, ?)
RETURNING id, name, type, config_json, created_at, updated_at
`

type CreateWidgetParams struct {
	Name       string `json:"name"`
	Type       string `json:"type"`
	ConfigJson string `json:"config_json"`
}

func (q *Queries) CreateWidget(ctx context.Context, arg CreateWidgetParams) (Widget, error) {
	row := q.db.QueryRowContext(ctx, createWidget, arg.Name, arg.Type, arg.ConfigJson)
	var i Widget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWidget = `-- name: DeleteWidget :exec
DELETE FROM widgets WHERE id = ?
`

func (q *Queries) DeleteWidget(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWidget, id)
	return err
}

const getWidget = `-- name: GetWidget :one
SELECT id, name, type, config_json, created_at, updated_at FROM widgets WHERE id = ?
`

func (q *Queries) GetWidget(ctx context.Context, id int64) (Widget, error) {
	row := q.db.QueryRowContext(ctx, getWidget, id)
	var i Widget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWidgets = `-- name: ListWidgets :many
SELECT id, name, type, config_json, created_at, updated_at FROM widgets ORDER BY name
`

func (q *Queries) ListWidgets(ctx context.Context) ([]Widget, error) {
	rows, err := q.db.QueryContext(ctx, listWidgets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Widget{}
	for rows.Next() {
		var i Widget
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.ConfigJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWidget = `-- name: UpdateWidget :exec
UPDATE widgets SET name = ?, config_json = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateWidgetParams struct {
	Name       string `json:"name"`
	ConfigJson string `json:"config_json"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateWidget(ctx context.Context, arg UpdateWidgetParams) error {
	_, err := q.db.ExecContext(ctx, updateWidget, arg.Name, arg.ConfigJson, arg.ID)
	return err
}
